name: 'pnpm Cache'
description: 'Restore or save pnpm store cache'

inputs:
  mode:
    description: 'Whether to restore or save the cache'
    required: true
  path:
    description: 'Custom cache path (defaults to pnpm store path)'
    required: false
  key-prefix:
    description: 'Cache key prefix (defaults to {runner.os}-pnpm-store)'
    required: false
  cache-hit:
    description: 'Whether cache was hit (required for save mode)'
    required: false
  cache-key:
    description: 'Cache key to use for saving (required for save mode)'
    required: false

outputs:
  cache-hit:
    description: 'Whether cache was restored'
    value: ${{ steps.cache-restore.outputs.cache-hit }}
  cache-key:
    description: 'Cache key for use in save step'
    value: ${{ steps.cache-restore.outputs.cache-primary-key }}

runs:
  using: 'composite'
  steps:
    # Restore mode steps
    - name: Get pnpm store directory
      if: inputs.mode == 'restore' && inputs.path == ''
      id: pnpm-store
      shell: bash
      run: echo "path=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Compute cache key prefix
      if: inputs.mode == 'restore'
      id: key-prefix
      shell: bash
      run: |
        if [ -n "${{ inputs.key-prefix }}" ]; then
          echo "value=${{ inputs.key-prefix }}" >> $GITHUB_OUTPUT
        else
          echo "value=${{ runner.os }}-pnpm-store" >> $GITHUB_OUTPUT
        fi

    - name: Restore pnpm cache
      if: inputs.mode == 'restore'
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.path || steps.pnpm-store.outputs.path }}
        key: ${{ steps.key-prefix.outputs.value }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ steps.key-prefix.outputs.value }}-

    # Save mode steps
    - name: Get pnpm store directory for save
      if: inputs.mode == 'save' && inputs.cache-hit != 'true' && inputs.path == ''
      id: pnpm-store-save
      shell: bash
      run: echo "path=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Save pnpm cache
      if: inputs.mode == 'save' && inputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.path || steps.pnpm-store-save.outputs.path }}
        key: ${{ inputs.cache-key }}
