export const STEP_INDICES = {
  PARENTS_COUNT: 0,
  PARENTS_DETAIL: 1,
  BIO_PARENTS: 2,
  SIBLINGS_COUNT: 3,
  SIBLINGS_DETAIL: 4,
  PARTNER: 5,
  CHILDREN_WITH_PARTNER_COUNT: 6,
  CHILDREN_WITH_PARTNER_DETAIL: 7,
  OTHER_CHILDREN_COUNT: 8,
  OTHER_CHILDREN_DETAIL: 9,
} as const;
