name: CI
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Set node version
      - uses: actions/setup-node@v2
        with:
          node-version: "12.14.1"
      - name: Set NPM 7
        run: npm install -g npm@7.6.3

      - name: ZIP development protocol
        run: zip Development.netcanvas * -r -0

      - name: Checkout protocol validation
        uses: actions/checkout@v2
        with:
          repository: complexdatacollective/protocol-validation
          ref: feature/schema-version-8
          path: protocol-validation

      - name: Install protocol validation
        run: |
          cd protocol-validation
          npm install

      - name: Validate protocol
        run: |
          cd protocol-validation
          npm run validate-protocol ../Development.netcanvas
